Repository 42-AI/bootcamp_machine-learning, pull requests merged in 2022-03, with the labels that each got.

#171 Changed X for y_hat when calling loss_ and loss_elem_
  module07/en.subject.tex
Labels: module02

#172 fixed add_intercept' docstring
  module05/en.subject.tex
Labels: module00

#173 fixed examples (issue #136)
  module06/en.subject.tex
Labels: module00

#174 clarifications & corrections for ml00-ex00 matrix instructions
  module05/en.subject.tex
Labels: module00

#186 #161 Module 04 - ex06 - Ridge: Inconsistence in the rules
  module09/en.subject.tex
  version
Labels: fixme

#187 fixed element alignment
  module09/en.subject.tex
Labels: module04

#194 fixed examples for ex03 of ml01
  module06/en.subject.tex
Labels: module01
